version: '3'

services:
    payload:
        container_name: payload
        image: node:18-alpine
        ports:
            - '3000:3000'
        volumes:
            - .:/home/node/app
            - node_modules:/home/node/app/node_modules
        working_dir: /home/node/app/
        command: sh -c "yarn install && yarn dev"
        depends_on:
            - mongo
        env_file:
            - .env

    mongo:
        container_name: mongo
        image: mongo:latest
        restart: always
        ports:
            - 27017:27017
        command: mongod --storageEngine=wiredTiger
        volumes:
            - data:/data/db
volumes:
    data:
    node_modules:
